"""initial schema

Revision ID: db76dd0e5888
Revises: 
Create Date: 2026-05-01 18:21:57.139095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db76dd0e5888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('person', 'project', 'repo', 'org', name='entitykind'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('browser', 'file', 'email', 'calendar', 'notion', 'obsidian', 'slack', 'github', name='source'), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.Enum('page', 'document', 'message', 'event', 'note', 'code_file', 'commit', name='kind'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_item_source')
    )
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_item_id'), 'chunks', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_item_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_table('items')
    op.drop_table('entities')
    # ### end Alembic commands ###
